Fixes 24h changes formatting
ping-pub/explorer pull request #544
Opened 2024-02-19 06:49 UTC by zenodeapp

Hi,

The `assets`-array for a chain wasn't being included in the `coingecko`-object when there was no `coingecko_id` set. This caused the exponent to show incorrectly formatted 24 hour changes on the Staking page. See an example of a chain that has a denom of 18, but gets treated as having 0: https://ping.pub/genesisL1/staking.

It should be fixed after this PR, but it might be better practice to name the object differently, since `coingecko` would assume the chain is available on CoinGecko.

2024-02-20 01:20 UTC, liangping requested changes
I would suggest you improve the format function. not here. 

it would raise other issues if you add empty coingecko_id here.

2024-02-20 18:51 UTC, zenodeapp commented
> I would suggest you improve the format function. not here.
> 
> it would raise other issues if you add empty coingecko_id here.

Right, I could do this, but may require a decoupling of the `exponent`. Will check it out for ya.

2024-02-20 19:28 UTC, zenodeapp commented
Hey @liangping, I changed it, think this should work? It prefers checking the coingecko object, then checks if it's a special denom, followed by finally looking it up by checking the AssetConfig.

This could all be refactored and optimized of course, but would fix this for now.

2024-02-22 02:36 UTC, liangping approved these changes

2024-02-22 02:37 UTC, merged